name: card-recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pillow
  - pip:
      - torch
      - torchvision
      - opencv-python
      - pytest
